-- {-# LANGUAGE TupleSections #-}

-- TODO: maybe move defaultBind somewhere else
module Language.Haskell.Liquid.Lava.SpecToLH (transSig, showppStripped, defaultBind, bops, buildins) where

-- import Data.List.Extra (replace)

-- (LHType(TVar, TDat, Buildin),BuildInTps)
import Control.Monad -- (liftM2,foldM,filterM)
import Control.Monad.Extra (ifM)
import Control.Monad.Reader
import qualified Data.Bifunctor as B
import qualified Data.HashMap.Strict as M
import Language.Fixpoint.Types (PPrint)
import qualified Language.Fixpoint.Types as F
import Language.Haskell.Liquid.Types.RType (PVarV (PV), RTVar (RTVar), RTyCon (RTyCon), RTyVar (RTV), RTypeV (..), SpecType, UReftV (MkUReft))
import qualified Lava.InternalLH as ILH
import Lava.Misc
import Lava.Util
import Prelude

-- | Translation of an RTyCon as a builtin or as a type constructor
transCon :: Id -> RTyCon -> ILH.LHType
transCon modId (RTyCon tc [] _) =
  case M.lookup name buildins of
    Nothing | name == "()" -> ILH.unitTp
    Nothing -> ILH.TDat name
    Just typ -> ILH.Buildin typ
  where
    name = showppStripped modId tc
transCon _ c = error $ "Type constructor applied to type arguments not supported (no polymorphism): " ++ show c

showppStripped :: (PPrint a) => Id -> a -> String
showppStripped modId = stripLegalName modId . F.showpp

data InternalCont = ConstrArgsCtx (Maybe Id) [Id] deriving (Show)

-- TODO: replace with something that uses notations as defined in liquidhaskell source
internalConstrRef :: (PPrint a) => Id -> a -> Reader InternalCont Bool
internalConstrRef modId s = do
  intCont <- ask
  return $ case intCont of
    ConstrArgsCtx Nothing _ -> False
    ConstrArgsCtx (Just c) args -> case parseConstrPred modId s of
      (Just "is", _) -> True
      _ -> case getFuncArgName modId s of
        (Just c', _) | stripLegalName modId c' == c -> True
        (Just x, _) | x `elem` args -> False
        (Just c', x) -> showppStripped modId c' `elem` c : args && x `elem` args
        (Nothing, "") -> True
        _ -> False

getFuncArgName :: (PPrint a) => Id -> a -> (Maybe Id, Id)
getFuncArgName modId symb = go sym
  where
    -- \| local name generated by parser
    go s | length (filter ('$' ==) s) == 1 && "$db##" `isInfixOf` s = case split '$' s of
      [n, s'] -> (Nothing, stripLegalName modId res)
        where
          res :: Id
          res = case split '#' s' of
            ["db", "", num] -> n ++ num
            _ -> n ++ s'
      _ -> error "Impossible case"
    go s = case split '#' s of
      [n, "", func] -> (Just (stripLegalName modId n), stripLegalName modId func)
      [func] -> (Nothing, stripLegalName modId func)
      [_, "", n, "", func] -> (Just (stripLegalName modId n), stripLegalName modId func)
      other | length other > 6 -> (Nothing, "") -- go . concat . drop 2 $ split '#' s
      _ -> error $ "Error in SpecToLH.getFuncArgName: " ++ sym
    sym = F.showpp symb

transVarName :: (PPrint a) => Id -> a -> String
transVarName modId x = case getFuncArgName modId x of
  (Just n, func) -> stripLegalName modId $ func ++ "." ++ n
  (Nothing, "") -> "illegalInternalName"
  (Nothing, func) -> func

parseConstrPred :: (PPrint a) => Id -> a -> (Maybe Id, Id)
parseConstrPred modId symb = case split '$' $ F.showpp symb of
  [n, func] -> (Just (stripLegalName modId n), stripLegalName modId func)
  [func] -> (Nothing, stripLegalName modId func)
  _ -> error $ "Error in SpecToLH.parseConstrPred: " ++ F.showpp symb

-- | defaultBind({x:A | r}) = (x, {x:A | r})
defaultBind :: ILH.RefType -> (Id, ILH.RefType)
defaultBind x = (ILH.argName x, x)

-- | Translation of a LH SpecType to a refined argument {x: A | r}
--
-- > transType(RVar n ref) = {x: x | transRef(x,ref)} -- where x = showName n
-- > transType({f: (arg -> ret) | ref}) = {f: (x:transType(arg) -> transType(ret)) | transRef(x,ref)} -- where transType(arg) = {x:_ | _}
-- > transType(RAllT (RVar n _) typ ref) = {x:tp | transRef(x,ref)} -- where transType(typ) = {_:tp | _} and x = showName n
-- > transType(PType (PV n _ _ _) typ) = {n:tp | true} -- where transType(typ) = {_:tp | _}
-- > transType(RApp f _ _ reft) = {x: (transCon f) | transRef(x,reft)} -- where reft = {x: _ | _}
transType :: Id -> InternalCont -> SpecType -> ILH.RefType
transType modId intCont specTp = case specTp of
  -- \| Type variables
  RVar n ref -> case x of
    "()" -> ILH.RefType x ILH.unitTp reft
    -- "Nat" -> ILH.RefType x (ILH.Buildin ILH.Integer) (ILH.Bop ILH.And (ILH.Bop ILH.Geq (ILH.Var x) (ILH.IntLit 0)) reft)
    _ -> ILH.RefType x (ILH.TDat x) reft
    where
      x = showName n
      reft = transRef x ref
  -- \| Functions
  RFun f _ arg ret ref -> {- traceFuncRet ["transType", transVarName f, showP funT, showP refT] $ -} ILH.RefType (transVarName modId f) funT refT
    where
      x = transVarName modId f
      funT = mkFun x arg ret
      ILH.Pi (x', _) _ = funT
      -- ToDo: Come up with a cleaner more self-contained way to do this. Maybe add foralls to LHFormulas and use them here
      -- ugly workaround: replaces variable s with x from function argument, this will later be universally quantified
      refT = transRef x' ref
  -- \| Forall?
  RAllT (RTVar (RTV n) _) typ ref -> ILH.RefType x tp r
    where
      x = showName n
      tp = transTp typ
      r = transRef x ref
  -- \| Abstract refinements
  RAllP (PV n _ _ _) typ -> ILH.RefType x tp ILH.ttTm -- ILH.RefType id tp reft
    where
      x = showName n
      tp = transTp typ
  -- \| Application of type constructor/builtin to types
  RApp f _ _ reft -> ILH.RefType x transT r
    where
      transT = transCon modId f
      x = refVar reft
      r = transRef x reft
  {-RAllE s typ _ -> undefined where
        x = transVarName s
        tp = transTp typ
  REx s tp ret -> undefined
  RExprArg _ -> undefined
  RAppTy rt_arg rt_res reft -> undefined where
        argTp = transTp rt_arg
        retTp = transTp rt_res
        x = refVar reft
        r = transRef x reft -}
  _ -> error "Unsupported SpecType found in SpecToLH.transType"
  where
    showName :: (Show a) => a -> String
    showName = transVarName modId . show
    refVar = transVarName modId . fst . transRefType
    transRef x r =
      let (s, ref) = transRefType r
       in sub (transVarName modId s) (ILH.Var x) ref
    -- MKUreft (F.Reft (s, tm)) is the representation of {s:_ | tm}
    transRefType (MkUReft (F.Reft (s, tm)) _) = (s, runReader (transExp modId tm) intCont)
    transTp = ILH.argTp . transType modId intCont
    mkFun :: Id -> SpecType -> SpecType -> ILH.LHType
    mkFun x arg ret = ILH.Pi (defaultBind argTS) (transType modId intCont ret)
      where
        (ILH.RefType x' aT xp') = transType modId intCont arg
        argTS = ILH.RefType x aT (sub x' (ILH.Var x) xp')

isInternal :: (PPrint a) => Id -> a -> Reader InternalCont Bool
isInternal = internalConstrRef

internal :: Id -> F.Expr -> Reader InternalCont Bool
internal modId = internal_aux
  where
    internal_aux (F.PAtom _ e1 e2) = liftM2 (||) (internal_aux e1) (internal_aux e2)
    internal_aux (F.EApp f t') = liftM2 (||) (internal_aux f) (internal_aux t')
    internal_aux (F.EVar sym) = isInternal modId sym
    internal_aux (F.PAnd es) = foldM (\acc x -> (&& acc) <$> internal_aux x) True es -- all internal es
    internal_aux (F.PNot form) = internal_aux form
    internal_aux (F.EBin {}) = return False
    internal_aux _ = return False

-- | Translation of an LH-fixpoint Types.Expr (predicates used for refinements)
--
-- > transExpr(e) = tt -- if e is internal
-- > transExpr(brel e1 e2) = brel (transExpr e1) (transExpr e2)
-- > transExpr((…(x e1)…) en) = x [transExpr(e1), …, transExpr(en)]
-- > transExpr(x) = x
-- > transExpr(e1 && … && en) = &&_{ei not internal} trans(ei)
-- > transExpr(e1 <=> e2) = transExpr(e1) == transExpr(e2)
-- > transExpr(e1 => e2) = transExpr(e1) => transExpr(e2)
-- > transExpr(sym) = sym
-- > transExpr(i ∈ Int) = i
-- > transExpr(f ∈ Float) = f
-- > transExpr(s ∈ String) = s
-- > transExpr(not e) = not (transExpr e)
-- > transExpr(Ebin f e1 e2) = Ebin (transExpr e1) (transExpr e2)
-- > transExpr(if e1 then e2 else e3) = (e1 && e2) || (not e1 && e3)
-- > transExpr(or [e1,…,en])= ||_{ei} trans(ei)
transExp :: Id -> F.Expr -> Reader InternalCont ILH.LHSimpleTerm
transExp modId term = transExpr term
  where
    transExpr :: F.Expr -> Reader InternalCont ILH.LHSimpleTerm
    transExpr term =
      ifM (internal modId term) (return ILH.ttTm) $
        case term of
          F.PAtom brel e1 e2 ->
            ILH.Bop (transBrel brel) <$> transExpr e1 <*> transExpr e2
          app@(F.EApp {}) ->
            let (F.EVar f, ts) = flattenFixApp app
             in ILH.App (ILH.Var $ transVarName modId f) <$> mapM transExpr ts
          F.EVar sym -> return res
            where
              s = transVarName modId sym
              res = case s of
                "True" -> ILH.ttTm
                "False" -> ILH.ffTm
                _ -> ILH.Var s
          F.PAnd es -> do
            refs' <- filterM (fmap not . isInternal modId) es
            refs'' <- mapM transExpr refs'
            return $ case refs'' of
              [] -> ILH.ttTm
              [r] -> r
              r : rs -> foldl (ILH.Bop ILH.And) r rs
          F.POr es -> do
            rs <- mapM transExpr es
            return $ case rs of
              [] -> ILH.ttTm -- [LP] An empty disjunction should be false no?
              [r] -> r
              r : rs' -> foldl (ILH.Bop ILH.Or) r rs'
          F.PIff ante concl ->
            ILH.Bop ILH.Eq <$> transExpr ante <*> transExpr concl
          F.PImp ante concl ->
            ILH.Bop ILH.Impl <$> transExpr ante <*> transExpr concl
          F.ECon (F.I i) -> return $ ILH.IntLit i
          F.ECon (F.R d) -> return $ ILH.FloatLit d
          F.ECon (F.L str _) -> return . ILH.StringLit $ show str
          F.PNot form -> ILH.Neg <$> transExpr form
          F.EBin f e1 e2
            | not (null op) ->
                ILH.Bop (fromJust op) <$> transExpr e1 <*> transExpr e2
            where
              op = M.lookup (F.showpp f) bops
          F.EIte cond thenE elseE -> do
            cTm <- transExpr cond
            tTm <- transExpr thenE
            eTm <- transExpr elseE
            return $ ILH.Bop ILH.Or (ILH.Bop ILH.And cTm tTm) (ILH.Bop ILH.And (ILH.Neg cTm) eTm)
          F.ESym sym -> error $ "Uninterpreted symbol encountered: " ++ show sym
          _ -> error $ "undefined expr translation: \n" ++ F.showpp term

{- mkITE c t e = ILH.Let x (ILH.LHTerm $ ILH.BasicTerm c) (ILH.LHTerm $
  ILH.Case x [(trueId, [], ILH.LHTerm $ t),(falseId, [], ILH.LHTerm $ e)] False) where
  x = "x_"++replace " " "_" (show c)
  trueId = show $ ILH.BoolLit True
  falseId = show $ ILH.BoolLit False -}

flattenFixApp :: F.Expr -> (F.Expr, [F.Expr])
flattenFixApp v@F.EVar {} = (v, [])
flattenFixApp (F.EApp f t) = (++ [t]) `B.second` flattenFixApp f
flattenFixApp _ = error "Application expected in SpecToLH.flattenFixApp."

-- | Translation of an arrow type
--
-- > transFun({f_1: t1 → {f_2: t_2 → {… → {f_n: t_n → t | _} … } | _} | _}) = ([(f_1, transType t_1), …, (f_n, transType t_n)], transType t) -- where n ≥ 0
-- > -- with some subtleties on the names, that relies on an additional context parameter
transFun :: Id -> Maybe Id -> SpecType -> ILH.ArrType
transFun modId fO spTp@(RFun g _ _ _ _) = go spTp [showppStripped modId g]
  where
    go :: SpecType -> [Id] -> ILH.ArrType
    -- TODO: put an error or a warning if the ignored refinement is not trivial
    go (RFun f _ tin tout _) vars = ILH.ArrType ((n, trans tin) : argsTl) ret
      where
        (nO, func) = getFuncArgName modId f
        n = fromMaybe func nO
        ILH.ArrType argsTl ret = go tout (n : vars)
        trans = transType modId (ConstrArgsCtx (Just n) vars)
    go spTp' vars = ILH.ArrType [] spTpT
      where
        f = maybe (showppStripped modId g) (stripLegalName modId) fO
        spTpT = transType modId (ConstrArgsCtx (Just f) vars) spTp'
transFun modId fO spTp = ILH.ArrType [] spTpT
  where
    intCont = ConstrArgsCtx (stripLegalName modId <$> fO) []
    spTpT = transType modId intCont spTp

-- | Translation of a specification of LH SpecType
transSig :: Id -> Maybe Id -> SpecType -> ILH.ArrType
transSig = transFun

-- | Trivial translation of binary relations
transBrel :: F.Brel -> ILH.Bop
transBrel F.Eq = ILH.Eq
transBrel F.Ne = ILH.Neq
transBrel F.Ge = ILH.Geq
transBrel F.Le = ILH.Leq
transBrel F.Gt = ILH.Gt
transBrel F.Lt = ILH.Lt
transBrel rel = error $ "Undefined brel translation: " ++ show rel

-- | LH builtin binary operators (on Int) (in Fixpoint, also RTimes (*.) and RDiv (/.), but not in CoreToLogic)
bops :: M.HashMap String ILH.Bop
bops =
  M.fromList
    [ ("+", ILH.Plus),
      ("-", ILH.Minus),
      ("*", ILH.Times),
      ("/", ILH.Div),
      ("%", ILH.Mod),
      ("==", ILH.Eq),
      ("/=", ILH.Neq),
      (">=", ILH.Geq),
      (">", ILH.Gt),
      ("<=", ILH.Leq),
      ("<", ILH.Lt)
    ]

-- | LH builtin types
buildins :: M.HashMap String ILH.BuildInTps
buildins =
  M.fromList
    [ ("Integer", ILH.Integer),
      ("Int", ILH.Integer),
      ("Float", ILH.Double)
    ]
